# Generated by Django 5.2.2 on 2025-06-09 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vote_data', models.TextField()),
                ('previous_hash', models.CharField(max_length=256)),
                ('hash', models.CharField(max_length=256)),
                ('nonce', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('eligible_departments', models.ManyToManyField(to='account.department')),
            ],
            options={
                'permissions': [('can_vote', 'Can vote in categories'), ('can_view_results', 'Can view voting results'), ('can_verify_blockchain', 'Can verify blockchain integrity')],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='candidates/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votingSystem.category')),
            ],
        ),
    ]
